Add submission dir check

diff --git a/subprepare b/subprepare
--- a/subprepare
+++ b/subprepare
@@ -1,17 +1,23 @@
 #!/usr/bin/env bash
 
-username=morri2wj
-name=$1
+name=$1 # name of assignment, first arg
 usage="Usage: subprepare (assignment name)"
 
+username=morri2wj
 class=cs361
 semester=f23
 prof=kirkpams
-rootdir=/cs/students/$class/$semester/$prof
 
+rootdir=/cs/students/$class/$semester/$prof
 if [[ ! -d $rootdir ]]; then
     echo "Content root directory not found: $rootdir"
     echo $usage
+    exit 1
+fi
+
+submissiondir=$rootdir/submit/$username
+if [[ ! -d "$submissiondir" ]]; then
+    echo "Submission directory $submissiondir not found."
     exit 1
 fi
 
