Add subprepare lab/pa check

diff --git a/subprepare b/subprepare
--- a/subprepare
+++ b/subprepare
@@ -1,29 +1,40 @@
 #!/usr/bin/env bash
 
-usage="Usage: subprepare (assignment name)"
+usage="Usage: subprepare [lab/pa] [assignment name]"
 
 username=morri2wj
 class=cs361
 semester=f23
 prof=kirkpams
 
-name=$1 # name of assignment, first arg
-if [[ "$#" -eq 0 ]]; then
-    echo "Specify a lab/project name!"
+# Validate args
+# EXPECTED: subprepare (whether lab or pa) (name)
+
+islab=$1 # whether is lab or is pa. This determines where the project will be placed.
+name=$2 # name of assignment, first arg
+
+if [[ "$#" -ne 2 ]]; then
     echo $usage
     exit 1
 fi
-
-if [[ "$#" -gt 1 ]]; then
-    echo "Too many args!"
-    echo $usage
-    exit 1
-fi 
 
 rootdir=/cs/students/$class/$semester/$prof
 if [[ ! -d $rootdir ]]; then
     echo "Content root directory not found: $rootdir"
     exit 1
+fi
+
+subroot=""
+if [[ "$islab" = "lab" ]]; then
+    echo "Preparing repository for lab submission"
+    subroot="$rootdir/submit/$username"
+elif [[ "$islab" = "pa" ]]; then
+    echo "Prepare repository for pa submission"
+    rootdir="$rootdir/teams/$username"
+else
+    echo "Invalid input: $islab. Specify lab or pa"
+    echo $usage
+    exit 1 
 fi
 
 subroot=$rootdir/submit/$username
